[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
anchor_counter = "FiRe9FmRnk5HXyfNaYu7CFn2YDL67YMzo98znwcUaCq1"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/durvesh/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
